In [1]:
my_list = [1,3,4,55,2]

In [2]:
my_list

[1, 3, 4, 55, 2]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([ 1,  3,  4, 55,  2])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones([2,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.random.rand(5,5)

array([[0.62884299, 0.77777831, 0.8828142 , 0.50154465, 0.3453034 ],
       [0.34194772, 0.9053573 , 0.14388411, 0.42711275, 0.45754119],
       [0.04349031, 0.94772364, 0.2594287 , 0.68693149, 0.31410665],
       [0.6940616 , 0.60402373, 0.31318156, 0.04137698, 0.80523326],
       [0.66642612, 0.23880638, 0.0814179 , 0.29268147, 0.49905854]])

In [24]:
np.random.randn(2)

array([0.91534582, 1.81842521])

In [27]:
np.random.rand(5,5)

array([[0.12098148, 0.64694117, 0.28004396, 0.20405346, 0.11238586],
       [0.77079644, 0.89306478, 0.68216241, 0.05456399, 0.5030028 ],
       [0.1540893 , 0.4731321 , 0.74003334, 0.94191436, 0.33854812],
       [0.02540749, 0.88030675, 0.29559646, 0.16712427, 0.87705263],
       [0.79329914, 0.2874793 , 0.16919097, 0.66315282, 0.93072106]])

In [28]:
np.random.randint(1,100)

16

In [29]:
np.random.randint(1,100,10)

array([87, 49, 86, 94, 36, 64, 72, 33, 65, 44])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,10)

In [34]:
ranarr

array([48, 32, 35, 32,  0, 30, 38, 31,  6, 35])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([48, 32, 35, 32,  0, 30, 38, 31,  6, 35])

In [40]:
ranarr.max()

48

In [41]:
ranarr.min()

0

In [42]:
ranarr.argmax()

0

In [43]:
ranarr.argmin()

4

In [45]:
arr.shape

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')

In [53]:
from numpy.random import randint

In [54]:
randint(2,10)

8